### ISSUE TITLE
support for vertical and horizontal scrolling

### ISSUE THREAD

**Issue by philippkuehn** [kutlugsahin/smooth-dnd#1]
In your demo I can see that there is support for vertical **OR** horizontal scrolling but not both. One scenario is a trello like board.

Would be really nice to see that feature!

**Comment by kutlugsahin** [comment]
I completely agree. Its in the to do list. It will be one of the next improvements to be implemented. Thanks

**Comment by kutlugsahin** [comment]
Feature is implemented in v0.3.7

**Comment by youcanping** [comment]
support both  vertical and horizontal ?
