### ISSUE TITLE
Enable cursor on ghost element?

### ISSUE THREAD

**Issue by cheshireoctopus** [kutlugsahin/smooth-dnd#14]
@kutlugsahin - thank you for maintaining this library and `react-smooth-dnd`.

Am running into an issue using `react-smooth-dnd` where CSS classes passed into `dragClass` do not acknowledge the `cursor` property.

I see that this property is comment out [here](https://github.com/kutlugsahin/smooth-dnd/blob/d0d8fc2b9a6be4d3412f279d2e4223869de8de8d/src/mediator.js#L89).

Should we not be overriding the `cursor` property?

**Comment by kutlugsahin** [comment]
hey @cheshireoctopus,
The cursor problem is fixed on latest smooth-dnd and react-smooth-dnd versions. Hope it did't take so long. Cheers!

**Comment by cheshireoctopus** [comment]
@kutlugsahin - appreciate the followup 👍
