### ISSUE TITLE
IE 9 and IE 10 support

### ISSUE THREAD

**Issue by happier2** [kutlugsahin/smooth-dnd#17]
It seems like that the [demo page](https://kutlugsahin.github.io/smooth-dnd-demo/) don't support IE 9 and IE 10. Error reported in ie console is 'SCRIPT5009: “Set” is undefined'. Maybe, you should include babelpollyfill in this demo page, so that this demo page supports IE 9 and IE 10.

**Comment by kutlugsahin** [comment]
hey @happier2. Unfortunately the library itself does not support IE9 and IE10. It targets IE11 and above.
Cheers!
