### ISSUE TITLE
vue.js wrapper

### ISSUE THREAD

**Issue by philippkuehn** [kutlugsahin/smooth-dnd#2]
I saw this is planned but there is no opened issue related to it. So I'll leave this here.

**Comment by kutlugsahin** [comment]
Hi @philippkuehn 
I will start working on angular wrappers in couple of days and on Vue after that.

**Comment by kutlugsahin** [comment]
[https://github.com/kutlugsahin/vue-smooth-dnd](https://github.com/kutlugsahin/vue-smooth-dnd)
