### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by colek42** [kutlugsahin/smooth-dnd#3]
The demo page does not work in IE11.

![image](https://user-images.githubusercontent.com/6634325/38373629-af7e829a-38bf-11e8-8b6b-c61c8024c947.png)

**Comment by kutlugsahin** [comment]
Hi @colek42 thanks for submitting issue. There was missing polyfills for IE11. 
It is now fixed in the version 0.3.0 of smooth-dnd and also in the demo.

**Comment by colek42** [comment]
Works perfectly now!  Thanks for fixing it so quick, and open sourcing!

**Comment by kutlugsahin** [comment]
Np, cheers!
