### ISSUE TITLE
Cannot find name 'ReturnType'

### ISSUE THREAD

**Issue by BloodChiefStromberg** [kutlugsahin/smooth-dnd#41]
Seeing:
```
ERROR in node_modules/smooth-dnd/dist/src/interfaces.d.ts(122,13): error TS2304: Cannot find name 'ReturnType'.
```
It was working the other day on 0.8.6, but sometime started feeling. Tried upgrading and downgrading without success. Any idea what's going on here?

**Comment by kutlugsahin** [comment]
Does your ts compiler trying to compile it? Or maybe your ts version does not have ReturnType type

**Comment by kutlugsahin** [comment]
ts version should be >= 2.8
