### ISSUE TITLE
DropPreviewOptions.animationDuration miss-type

### ISSUE THREAD

**Issue by joshuacoles** [kutlugsahin/smooth-dnd#46]
Hey, I was playing with the React Cards example and I noticed the `animationDuration` property on [`DropPreviewOptions`](https://github.com/kutlugsahin/smooth-dnd/blob/c72505f48b081bd16ee6614202b79d8dee71c157/src/exportTypes.ts#L26) was typed as `string` where as on [`ContainerOptions`](https://github.com/kutlugsahin/smooth-dnd/blob/c72505f48b081bd16ee6614202b79d8dee71c157/src/exportTypes.ts#L46) is a `number` and its usages generally seem to be as a number. Is this a typo?

If so I am happy to PR to fix.

**Comment by kutlugsahin** [comment]
Yes indeed it's a typo. PR is welcome :)
