### ISSUE TITLE
Draggable element is always dragged from center, not mouse coordinates

### ISSUE THREAD

**Issue by johannes-z** [kutlugsahin/smooth-dnd#48]
When you drag and drop an element, it always uses its center as its origin, rather than the mouse coordinates of the mousedown event.

**Comment by kutlugsahin** [comment]
Yes that's right. Center point of the element is used for collusion detection which make it feel more natural and physical. But I have a plan to provide an api to change that to mouse position or to adjust it to the needs.

**Comment by johannes-z** [comment]
@kutlugsahin I agree with what you said, just a quick info why this is needed: If you drag a bigger element into i.e. a column that's smaller, you'd have to drag it off-screen for it to snap, as shown in this paint masterpiece:

![image](https://user-images.githubusercontent.com/9069888/56137726-be5c5a00-5f95-11e9-9376-949836305ca0.png)
