### ISSUE TITLE
Svelte.js wrapper

### ISSUE THREAD

**Issue by mspanish** [kutlugsahin/smooth-dnd#5]
[Svelte](https://svelte.technology) is pretty awesome to work with - and stacks up as one of the fastest tools out there, if you haven't heard of it! A wrapper for Svelte would be awesome...

**Comment by kutlugsahin** [comment]
@mspanish  Thanks for the heads up! I don't have a plan to implement wrappers for Svelte yet but since you are already familiar with it you can easily make your own wrappers and publish it. I recommend you to check react or angular wrappers to see how to do it.
