### ISSUE TITLE
Duplication in vertical groups

### ISSUE THREAD

**Issue by ElForastero** [kutlugsahin/smooth-dnd#6]
Screen recording: https://cl.ly/0g1U0C3C1M42
Sandbox: https://codesandbox.io/s/github/yashok111/dnd

How to repeat: start dragging from the bottom list to the upper one and drop the item in between lists.

**Comment by kutlugsahin** [comment]
hi @ElForastero,
Thanks for the repo and video to reproduce.
I will submit a fix asap. Will be ready in the next version.

**Comment by kutlugsahin** [comment]
Fixed in v0.1.9
[https://codesandbox.io/s/qkplk481y4](https://codesandbox.io/s/qkplk481y4)
Cheers!

**Comment by kutlugsahin** [comment]
vue-smooth-dnd v 0.1.9 
smooth-dnd v 0.4.9
