### ISSUE TITLE
Ghost is taking space between two vertical lists

### ISSUE THREAD

**Issue by pbelyaev** [kutlugsahin/smooth-dnd#8]
If you place two lists vertically and try to move one item from the first list to the second list the ghost will remain in the first list. It will generate an empty gap between two lists. Check the video out to see how it looks.

https://cl.ly/3E2l3z3b043E

**Comment by kutlugsahin** [comment]
Hi @pbelyaev,
That is because the container size remains the same when the dragged item is out of the container boundaries. That's by design now and make sense unless you want multiple containers placed one another act like one. Why not using one container instead of placing many vertically?
